### ISSUE TITLE
pmix-tests: ./xversion.py hanging

### ISSUE THREAD

**Issue by karasevb** [pmix/pmix#913]
I have got a hang when testing by `xversion.py`:
```
$./xversion.py --server-versions master --client-versions master -b
======================================================================
Server: master -> Client: master
============ PMIx Run  : Run simptest
Client /users/user/pmix_test/pmix-tests/crossversion/pmix-master/test/simple/simpclient

<hanging here, try Ctrl+C>

^CTraceback (most recent call last):
  File "./xversion.py", line 283, in <module>
    ret = run_test(bld_server, bld_client)
  File "./xversion.py", line 169, in run_test
    stdout=logfile, stderr=logfile, shell=False)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```
Here is process state while a hanging:
```
user  23825  0.2  0.0 151688  6240 pts/17   S+   04:55   0:00 /usr/bin/python ./xversion.py --server-versions master --client-versions master -b
user  23828  3.0  0.0 183872 10936 pts/17   Sl+  04:55   0:00 ./simptest -n 2 -e /users/user/pmix_test/pmix-tests/crossversion/pmix-master/test/simple/simpclient
user  23834  0.0  0.0      0     0 pts/17   Z+   04:55   0:00 [simpclient] <defunct>
```
I tried to use `./xversion.py` on different machines, some of them have different statistics of hangs. The hang is not 100% reproducible, but on some machines, it mostly hangs for almost all attempted runs.

The attempting to test directly always works well:
```
$./simptest -n 2 -e /users/user/pmix_test/pmix-tests/crossversion/pmix-master/test/simple/simpclient
...
Test finished OK!
```

**Comment by karasevb** [comment]
@rhc54 did you encounter a similar one?

**Comment by jjhursey** [comment]
From the discussion on Issue #909 it sounds like you got this working. Is this still a problem?

**Comment by rhc54** [comment]
FWIW: the error means that your system is block SIGCHLD, thus preventing simptest from harvesting the child when it terminates. We fixed this in OMPI, but saw no reason to backport such fixes to PMIx. However, you could do it directly yourself, and I can add that to the simptest program going forward.

**Comment by karasevb** [comment]
@rhc54 it still hanging with your PR #934
I try master-> master test:
```
user  32248  2.8  0.0 183872 10700 pts/82   Sl+  07:12   0:00 ./simptest -n 2 -e /users/user/pmix_test/pmix-tests/crossversion/pmix-master/test/simple/simpclient
user  32252  0.0  0.0      0     0 pts/82   Z+   07:12   0:00 [simpclient] <defunct>
```

**Comment by rhc54** [comment]
Hmmm...in what environment does this happen for most attempts?

**Comment by karasevb** [comment]
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Linux version 3.10.0-693.el7.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )

**Comment by rhc54** [comment]
Huh - that is really weird as I routinely test it on CentOS 7. Afraid I can't be of much help - I can only assume there is something odd in your environment that we aren't identifying.

@ggouaillardet Can you give the test script a shot? It would help if we could find at least one other person experiencing the same problem so we could compare scenarios.

**Comment by rhc54** [comment]
Pretty sure we can close this now - yes?

**Comment by karasevb** [comment]
I have not encountered this problem lately. Let's close this.
